#+TITLE: 博客搭建小记
#+AUTHOR: Zhiyong Ma
#+EMAIL: ccdevote@gmail.com


一直想搭建一个自己的博客，这两天终于下定决心搞起了，博客搭建的不算费力，中间投机
取巧了很多东西，下面就来记录一下整个搭建过程，希望对您有所帮助。


* 架构
  架构两个字貌似有点大，不过也找不到什么合适的词汇了。我的博客采用的是jekyll、
  github.io、Emacs、org-mode。具体的操作流程是用Emacs的org-mode写博客，然后直接生
  成为jekyll所需要的格式，再提交到github上。下面先简单介绍一下jekyll和github.io：
  + Jekyll（发音/'dʒiːk əl/，"杰克尔"）是一个静态站点生成器，它会根据网页源码生成
    静态文件。它提供了模板、变量、插件等功能，所以实际上可以用来编写整个网站。
  + github.io 是github提供的一个博客平台吧，可以让我们写好的博客通过git管理（当然
    不止能写博客，还可以发挥想想做一些其他的事情了）github.io通过Jekyll生成网页内
    容，也就是说我们写好了一个符合Jekyll规范的博文，然后提交到github上就就什么都
    不用管了，github会帮我们生成好网页，然后我们可以通过github.io上绑定的域名访
    问。
* 搭建步骤
** 在github上创建空间
   如果想通过github托管项目，那么最重要最重要的事情就是……申请一个github帐号。然
   后按照下面的步骤操作：
   + 创建一个repository,命名为 username.github.io,uername是你的用户名。
   + 检出到本地
     #+BEGIN_SRC python
     git clone username.github.io blog
     #+END_SRC
   + 写一个网页测试一下
     #+BEGIN_SRC python
     cd blog
     echo "hello world" >> index.html
     git add index.html
     git commit -m "test my blog"
     git push
     #+END_SRC
     提交之后等几分钟，解析生效后我们就可以通过 http://username.github.io 进行访问
     了。


** 安装Jekyll
   关于Jekyll我不想解释太多，具体的安装方式可以参考官方文档 http://jekyllrb.com/
   如果需要中文文档那么请参考 http://jekyllcn.com 或者
   http://www.ruanyifeng.com/blog/2012/08/blogging_with_jekyll.html 之所以没有详
   细介绍是因为我也没有仔细去看。但是不仔细看也是可以做出来自己的博客的，对！那
   就时fork！ github上有很多牛人使用Jekyll开发自己的博客了，我们找一个自己喜欢的
   fork下来修改一下就可以了（这才是真正的懒人博客）毕竟写博客的目的不是为了造一
   个博客呀…… 我fork的是这个（ https://github.com/mojombo ）fork下来我们还需要做
   下面几件事情：
   + 根据自己的口味修改，主要就是修改_ layout/目录下的模板还有css、js、images等等
   + 启动Jekyll测试
     #+BEGIN_SRC python
     jekyll serve -w #开启Jekyll服务器
     #+END_SRC
     启动成功以后会提示绑定在0.0.0.0:4000端口上，我们可以在浏览器中访问这个地址，
     就能够看到博客的效果了。
   接下来给大家介绍一下Jekyll的运行原理：
   + Jekyll 在启动的时候会读取_ config.yml，这里主要是一些配置信息，详细参考官网
   + 启动后默认会把_ posts目录下的文件生成博客，这些文件需要有一个符合YAML的头部
     信息才会被Jekyll解析，如：
     #+BEGIN_SRC python
     ---
     layout: post
     title : hello world
     ---
     #+END_SRC
     这个简短的头信息指定了布局模板和文章标题。此外，还需要有符合格式的文件名，
     默认为日期-文件名.html 当然我们可以通过_ config.yml进行配置
     #+BEGIN_SRC python
     2014-02-12-博客小记.html
     #+END_SRC
     这是标准默认的文件名。

** 书写博客
   Emacs的org-mode是一个写博客的神器，他的好处不是本文的重点，我也就不再赘述，下
   面主要介绍以下如何用Emacs快速的写出符合Jekyll的博客，有标准的头，有合理的文件
   名……原始的方法是这样的：
   + 用org-mode写博客
   + 导出为html文件
   + 添加合理的文件头
   + 修改一个合理的文件名
   + 移动到_ posts 目录中
   额，太繁琐了，有没有更好的方法呢？必须的…… 更好的方法需要一个Emacs的插件，这
   个插件时网上一个大神的杰作，我也是拿来用的。名字叫org-jekyll-mode (
   https://github.com/jsuper/org-jekyll-mode ) 这个插件方便好用，优势如下：
   + 可以直接创建出文件名带有时间的文件
   + 可以直接从emacs中导出到_ posts 目录中
   + 可以只导出body里面的内容并且添加了文件头
   如此一来原始方法的5步操作就可以一步搞定了，是不是很省心呀？下面我们就来介绍以
   下如何安装配置org-jekyll-mode：
   + 下载org-jekyll-mode
     #+BEGIN_SRC python
     git clone https://github.com/jsuper/org-jekyll-mode
     #+END_SRC
   + 安装org-jekyll-mode *org-jekyll-mode* 依赖org-mode 8.0版本，首先要确保你的版
     本对应，在Emacs中可以通过如下指令查看:
     #+BEGIN_SRC python
     M x org-version
     #+END_SRC
     如果显示的是8.0或者更高的版本那么就可以继续安装了,配置.emacs
     #+BEGIN_SRC lisp
       (add-to-list 'load-path "path to org-jekyll-mode")
       (require 'org-jekyll-mode)
       ;;设定jekyll路径--你的博客路径
       (setq org-jekyll/jekyll-project-root "path to you jekyll home")
       ;;设定org文件存放的地址--博客源文件存放地址
       (setq org-jekyll/org-mode-project-root "/home/soft/document/blog/org")
     #+END_SRC
     如此一来，就安装完成了，打开emacs 执行
     #+BEGIN_SRC python
     M x org-jekyll-mode
     C c C d  # 根据提示输入文件名就可以创建出以当前日期为前缀的文件
     C c p    # 发布当前文件到_ posts目录中
     #+END_SRC
     关于org-jekyll-mode的详细介绍可以参考
     http://blog.sina.com.cn/s/blog_c589e9cd0101iji8.html
   这样通过Emacs写的博客就发布到Jekyll上了，我们可以访问localhost:4000查看一
   下。


** 发布博客
   博客书写完以后就是要发布到github上了，然后别人就可以通过
   your-username.github.io访问你的博客了。
   #+BEGIN_SRC python
   git add .
   git commmit -m " my first blog"
   git push
   #+END_SRC
   还是等一小会就可以在github上访问了


** 绑定自己的域名
   如果你有自己的域名，那么只需要通过简单的设置就可以通过自己的域名访问博客。创
   建一个名为CNAME的文件放在你的博客目录中，文件中写入你的域名，然后提交就可以了。
   过一段时间域名解析生效就可以访问了。
